# fly.toml app configuration file generated for fast-zero-divine-water-3043 on 2025-02-17T18:27:27-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fast-zero-divine-water-3043'
primary_region = 'gig'

[build]

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
